name: Push-CI

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'

concurrency:
  group: push-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kotlin-pipeline:
    uses: TomasGC/condor/.github/workflows/kotlin-push-ci.yml@main
    secrets: inherit
    with:
      app-name: anglerfish
      unit-tasks: '[":core:test", ":app:testDebugUnitTest"]'
      integration-mock-tasks: '[":core:integrationMock"]'
      integration-real-tasks: '[":core:integrationReal"]'
      instrumented-task: ":app-instrumented:connectedDebugAndroidTest"
      coverage-threshold: 0

  python-pipeline:
    uses: TomasGC/condor/.github/workflows/python-push-ci.yml@main
    with:
      skip-on-no-changes: true
